# Generated by Django 5.1.6 on 2025-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
