# Generated by Django 5.1.6 on 2025-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_custom_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_first_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_last_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Отчество'),
        ),
    ]
