# Generated by Django 5.1.6 on 2025-03-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerimage',
            options={'verbose_name': 'Изображение заголовка', 'verbose_name_plural': 'Изображения заголовка'},
        ),
    ]
