# Generated by Django 5.1.4 on 2024-12-17 10:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Подразделение')),
                ('type', models.CharField(choices=[('ORGANIZATION', 'Организация'), ('DEPARTMENT', 'Департамент'), ('DIVISION', 'Отдел')], help_text='Тип подразделения', max_length=50, verbose_name='Тип подразделения')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер для вывода на сайт')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Родительское подразделение', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='phonebook.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
    ]
