# Generated by Django 5.1.4 on 2024-12-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='name_kk',
            field=models.CharField(default=1, max_length=120, verbose_name='Название на казахском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(default=1, max_length=120, verbose_name='Название на русском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Порядковый номер для вывода на сайт', verbose_name='Порядковый номер для вывода на сайт'),
        ),
    ]
