# Generated by Django 5.1.4 on 2024-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_remove_department_name_department_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityphonenumber',
            name='number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='cityphonenumber',
            name='number_kk',
            field=models.CharField(default=1, max_length=20, verbose_name='Городской номер телефона на казахском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityphonenumber',
            name='number_ru',
            field=models.CharField(default=1, max_length=20, verbose_name='Городской номер телефона на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position_kk',
            field=models.CharField(default=1, max_length=100, verbose_name='Должность на казахском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(default=1, max_length=100, verbose_name='Должность на русском'),
            preserve_default=False,
        ),
    ]
