# Generated by Django 5.1.4 on 2024-12-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_remove_cityphonenumber_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityphonenumber',
            old_name='number_ru',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='cityphonenumber',
            name='number_kk',
        ),
    ]
