# Generated by Django 5.1.4 on 2024-12-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_rename_number_ru_cityphonenumber_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityphonenumber',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Городской номер телефона'),
        ),
    ]
