# Generated by Django 5.1.4 on 2024-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_employee_created_at_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
